/*
 * This file is generated by jOOQ.
 */
package com.sourceclear.agile.piplanning.service.jooq.tables.records;


import com.sourceclear.agile.piplanning.service.jooq.tables.Boards;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BoardsRecord extends UpdatableRecordImpl<BoardsRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = -1329173980;

    /**
     * Setter for <code>agile.boards.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>agile.boards.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>agile.boards.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>agile.boards.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>agile.boards.owner</code>.
     */
    public void setOwner(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>agile.boards.owner</code>.
     */
    public Long getOwner() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Boards.BOARDS.ID;
    }

    @Override
    public Field<String> field2() {
        return Boards.BOARDS.NAME;
    }

    @Override
    public Field<Long> field3() {
        return Boards.BOARDS.OWNER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getOwner();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getOwner();
    }

    @Override
    public BoardsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BoardsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BoardsRecord value3(Long value) {
        setOwner(value);
        return this;
    }

    @Override
    public BoardsRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BoardsRecord
     */
    public BoardsRecord() {
        super(Boards.BOARDS);
    }

    /**
     * Create a detached, initialised BoardsRecord
     */
    public BoardsRecord(Long id, String name, Long owner) {
        super(Boards.BOARDS);

        set(0, id);
        set(1, name);
        set(2, owner);
    }
}
