/*
 * This file is generated by jOOQ.
 */
package com.sourceclear.agile.piplanning.service.jooq.tables.records;


import com.sourceclear.agile.piplanning.service.jooq.tables.InvalidatedTokens;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvalidatedTokensRecord extends UpdatableRecordImpl<InvalidatedTokensRecord> implements Record4<Long, String, Long, OffsetDateTime> {

    private static final long serialVersionUID = 414880515;

    /**
     * Setter for <code>agile.invalidated_tokens.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>agile.invalidated_tokens.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>agile.invalidated_tokens.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>agile.invalidated_tokens.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>agile.invalidated_tokens.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>agile.invalidated_tokens.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>agile.invalidated_tokens.created_date</code>.
     */
    public void setCreatedDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>agile.invalidated_tokens.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Long, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Long, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InvalidatedTokens.INVALIDATED_TOKENS.ID;
    }

    @Override
    public Field<String> field2() {
        return InvalidatedTokens.INVALIDATED_TOKENS.VALUE;
    }

    @Override
    public Field<Long> field3() {
        return InvalidatedTokens.INVALIDATED_TOKENS.USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return InvalidatedTokens.INVALIDATED_TOKENS.CREATED_DATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public OffsetDateTime component4() {
        return getCreatedDate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public OffsetDateTime value4() {
        return getCreatedDate();
    }

    @Override
    public InvalidatedTokensRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InvalidatedTokensRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public InvalidatedTokensRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public InvalidatedTokensRecord value4(OffsetDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public InvalidatedTokensRecord values(Long value1, String value2, Long value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvalidatedTokensRecord
     */
    public InvalidatedTokensRecord() {
        super(InvalidatedTokens.INVALIDATED_TOKENS);
    }

    /**
     * Create a detached, initialised InvalidatedTokensRecord
     */
    public InvalidatedTokensRecord(Long id, String value, Long userId, OffsetDateTime createdDate) {
        super(InvalidatedTokens.INVALIDATED_TOKENS);

        set(0, id);
        set(1, value);
        set(2, userId);
        set(3, createdDate);
    }
}
