/*
 * This file is generated by jOOQ.
 */
package com.sourceclear.agile.piplanning.service.jooq.tables.records;


import com.sourceclear.agile.piplanning.service.jooq.tables.Notifications;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> implements Record5<Long, Long, String, Long, Boolean> {

    private static final long serialVersionUID = 1796799846;

    /**
     * Setter for <code>agile.notifications.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>agile.notifications.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>agile.notifications.recipient_id</code>.
     */
    public void setRecipientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>agile.notifications.recipient_id</code>.
     */
    public Long getRecipientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>agile.notifications.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>agile.notifications.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>agile.notifications.story_request_id</code>.
     */
    public void setStoryRequestId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>agile.notifications.story_request_id</code>.
     */
    public Long getStoryRequestId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>agile.notifications.acknowledged</code>.
     */
    public void setAcknowledged(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>agile.notifications.acknowledged</code>.
     */
    public Boolean getAcknowledged() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, Long, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, Long, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notifications.NOTIFICATIONS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Notifications.NOTIFICATIONS.RECIPIENT_ID;
    }

    @Override
    public Field<String> field3() {
        return Notifications.NOTIFICATIONS.TYPE;
    }

    @Override
    public Field<Long> field4() {
        return Notifications.NOTIFICATIONS.STORY_REQUEST_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return Notifications.NOTIFICATIONS.ACKNOWLEDGED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRecipientId();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public Long component4() {
        return getStoryRequestId();
    }

    @Override
    public Boolean component5() {
        return getAcknowledged();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRecipientId();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public Long value4() {
        return getStoryRequestId();
    }

    @Override
    public Boolean value5() {
        return getAcknowledged();
    }

    @Override
    public NotificationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationsRecord value2(Long value) {
        setRecipientId(value);
        return this;
    }

    @Override
    public NotificationsRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public NotificationsRecord value4(Long value) {
        setStoryRequestId(value);
        return this;
    }

    @Override
    public NotificationsRecord value5(Boolean value) {
        setAcknowledged(value);
        return this;
    }

    @Override
    public NotificationsRecord values(Long value1, Long value2, String value3, Long value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Long id, Long recipientId, String type, Long storyRequestId, Boolean acknowledged) {
        super(Notifications.NOTIFICATIONS);

        set(0, id);
        set(1, recipientId);
        set(2, type);
        set(3, storyRequestId);
        set(4, acknowledged);
    }
}
