/*
 * This file is generated by jOOQ.
 */
package com.sourceclear.agile.piplanning.service.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in agile
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>agile.accounts_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNTS_ID_SEQ = Internal.createSequence("accounts_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.boards_id_seq</code>
     */
    public static final Sequence<Long> BOARDS_ID_SEQ = Internal.createSequence("boards_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.epics_id_seq</code>
     */
    public static final Sequence<Long> EPICS_ID_SEQ = Internal.createSequence("epics_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.invalidated_tokens_id_seq</code>
     */
    public static final Sequence<Long> INVALIDATED_TOKENS_ID_SEQ = Internal.createSequence("invalidated_tokens_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.memberships_id_seq</code>
     */
    public static final Sequence<Long> MEMBERSHIPS_ID_SEQ = Internal.createSequence("memberships_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.notifications_id_seq</code>
     */
    public static final Sequence<Long> NOTIFICATIONS_ID_SEQ = Internal.createSequence("notifications_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.solutions_id_seq</code>
     */
    public static final Sequence<Long> SOLUTIONS_ID_SEQ = Internal.createSequence("solutions_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.sprints_id_seq</code>
     */
    public static final Sequence<Long> SPRINTS_ID_SEQ = Internal.createSequence("sprints_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.story_requests_id_seq</code>
     */
    public static final Sequence<Long> STORY_REQUESTS_ID_SEQ = Internal.createSequence("story_requests_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.tickets_id_seq</code>
     */
    public static final Sequence<Long> TICKETS_ID_SEQ = Internal.createSequence("tickets_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>agile.users_id_seq</code>
     */
    public static final Sequence<Long> USERS_ID_SEQ = Internal.createSequence("users_id_seq", Agile.AGILE, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
