/*
 * This file is generated by jOOQ.
 */
package com.sourceclear.agile.piplanning.service.jooq;


import com.sourceclear.agile.piplanning.service.jooq.tables.Accounts;
import com.sourceclear.agile.piplanning.service.jooq.tables.Boards;
import com.sourceclear.agile.piplanning.service.jooq.tables.Epics;
import com.sourceclear.agile.piplanning.service.jooq.tables.FlywaySchemaHistory;
import com.sourceclear.agile.piplanning.service.jooq.tables.InvalidatedTokens;
import com.sourceclear.agile.piplanning.service.jooq.tables.JiraCsv;
import com.sourceclear.agile.piplanning.service.jooq.tables.Memberships;
import com.sourceclear.agile.piplanning.service.jooq.tables.Solutions;
import com.sourceclear.agile.piplanning.service.jooq.tables.Sprints;
import com.sourceclear.agile.piplanning.service.jooq.tables.StoryRequests;
import com.sourceclear.agile.piplanning.service.jooq.tables.TicketDeps;
import com.sourceclear.agile.piplanning.service.jooq.tables.TicketPins;
import com.sourceclear.agile.piplanning.service.jooq.tables.Tickets;
import com.sourceclear.agile.piplanning.service.jooq.tables.Users;


/**
 * Convenience access to all tables in agile
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>agile.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>agile.boards</code>.
     */
    public static final Boards BOARDS = Boards.BOARDS;

    /**
     * The table <code>agile.epics</code>.
     */
    public static final Epics EPICS = Epics.EPICS;

    /**
     * The table <code>agile.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>agile.invalidated_tokens</code>.
     */
    public static final InvalidatedTokens INVALIDATED_TOKENS = InvalidatedTokens.INVALIDATED_TOKENS;

    /**
     * The table <code>agile.jira_csv</code>.
     */
    public static final JiraCsv JIRA_CSV = JiraCsv.JIRA_CSV;

    /**
     * The table <code>agile.memberships</code>.
     */
    public static final Memberships MEMBERSHIPS = Memberships.MEMBERSHIPS;

    /**
     * The table <code>agile.solutions</code>.
     */
    public static final Solutions SOLUTIONS = Solutions.SOLUTIONS;

    /**
     * The table <code>agile.sprints</code>.
     */
    public static final Sprints SPRINTS = Sprints.SPRINTS;

    /**
     * The table <code>agile.story_requests</code>.
     */
    public static final StoryRequests STORY_REQUESTS = StoryRequests.STORY_REQUESTS;

    /**
     * The table <code>agile.ticket_deps</code>.
     */
    public static final TicketDeps TICKET_DEPS = TicketDeps.TICKET_DEPS;

    /**
     * The table <code>agile.ticket_pins</code>.
     */
    public static final TicketPins TICKET_PINS = TicketPins.TICKET_PINS;

    /**
     * The table <code>agile.tickets</code>.
     */
    public static final Tickets TICKETS = Tickets.TICKETS;

    /**
     * The table <code>agile.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
