/*
 * This file is generated by jOOQ.
 */
package com.sourceclear.agile.piplanning.service.jooq.tables;


import com.sourceclear.agile.piplanning.service.jooq.Agile;
import com.sourceclear.agile.piplanning.service.jooq.Keys;
import com.sourceclear.agile.piplanning.service.jooq.tables.records.BoardsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Boards extends TableImpl<BoardsRecord> {

    private static final long serialVersionUID = 2073699375;

    /**
     * The reference instance of <code>agile.boards</code>
     */
    public static final Boards BOARDS = new Boards();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BoardsRecord> getRecordType() {
        return BoardsRecord.class;
    }

    /**
     * The column <code>agile.boards.id</code>.
     */
    public final TableField<BoardsRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('boards_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>agile.boards.name</code>.
     */
    public final TableField<BoardsRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>agile.boards.owner</code>.
     */
    public final TableField<BoardsRecord, Long> OWNER = createField(DSL.name("owner"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>agile.boards</code> table reference
     */
    public Boards() {
        this(DSL.name("boards"), null);
    }

    /**
     * Create an aliased <code>agile.boards</code> table reference
     */
    public Boards(String alias) {
        this(DSL.name(alias), BOARDS);
    }

    /**
     * Create an aliased <code>agile.boards</code> table reference
     */
    public Boards(Name alias) {
        this(alias, BOARDS);
    }

    private Boards(Name alias, Table<BoardsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Boards(Name alias, Table<BoardsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Boards(Table<O> child, ForeignKey<O, BoardsRecord> key) {
        super(child, key, BOARDS);
    }

    @Override
    public Schema getSchema() {
        return Agile.AGILE;
    }

    @Override
    public Identity<BoardsRecord, Long> getIdentity() {
        return Keys.IDENTITY_BOARDS;
    }

    @Override
    public UniqueKey<BoardsRecord> getPrimaryKey() {
        return Keys.BOARDS_PKEY;
    }

    @Override
    public List<UniqueKey<BoardsRecord>> getKeys() {
        return Arrays.<UniqueKey<BoardsRecord>>asList(Keys.BOARDS_PKEY);
    }

    @Override
    public List<ForeignKey<BoardsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BoardsRecord, ?>>asList(Keys.BOARDS__BOARDS_OWNER_FKEY);
    }

    public Users users() {
        return new Users(this, Keys.BOARDS__BOARDS_OWNER_FKEY);
    }

    @Override
    public Boards as(String alias) {
        return new Boards(DSL.name(alias), this);
    }

    @Override
    public Boards as(Name alias) {
        return new Boards(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Boards rename(String name) {
        return new Boards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Boards rename(Name name) {
        return new Boards(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
